### ISSUE TITLE
Using decorator doesn't count as usage by eslint

### ISSUE THREAD

**Issue by andreypopp** [babel/babel-eslint#72]
Have the following code:
```
import autobind from 'autobind-decorator';

class TextareaAutosize {
  ...

  @autobind
  _onChange(e) { ... }
}
```
which results into:
```
   7:7   error    autobind is defined but never used                                                no-unused-vars
```

**Comment by zdychacek** [comment]
+1

**Comment by RobertCZ** [comment]
Related: Using in decorator's parameters doesn't count as usage either

    import DataManager from 'DataManager'
    @inject(DataManager)

**Comment by gaearon** [comment]
This is currently the biggest blocker for using decorators. Would love to see this fixed!

**Comment by Benoss** [comment]
+1

**Comment by b2whats** [comment]
+1

**Comment by istarkov** [comment]
+1

**Comment by istarkov** [comment]
There is also no-shadow hint for such situation with decorator
```javascript
function blabla() {}

@blabla(() => 1)
export class Test {
}
```

gives
`Test is already declared i the upper scope. (no-shadow)`

**Comment by damassi** [comment]
Just ran into this as well.

**Comment by olanod** [comment]
:+1:

**Comment by gaearon** [comment]
I guess you can contribute: https://github.com/alexkuz/eslint-plugin-decorator

**Comment by andreypopp** [comment]
I think it should be fixed by "fixing" estraverse to visit decorator AST
nodes so escope can find identifiers within.

**Comment by hzoo** [comment]
Can work on this - I guess I'l be using the examples from https://github.com/wycats/javascript-decorators for tests?

**Comment by hzoo** [comment]
Did a PR: #105 (although failing on travis) - can someone else test to see if it fixes the issue for them? I tested locally and it's good.

**Comment by hzoo** [comment]
Should be fixed in 3.1.6!

**Comment by andreypopp** [comment]
Thank you!

**Comment by gaearon** [comment]
@hzoo You are awesome. Thank you *so* much.

**Comment by gcanti** [comment]
Thanks @hzoo !

**Comment by raymond-h** [comment]
This feature apparently was broken sometime between releases `v3.1.25` and `v3.1.28`, and still doesn't work as of `v4.0.5`.

**Comment by hzoo** [comment]
Nothing was changed related to decorators in the last few releases - most likely an issue with babel. I would either wait for the next release or pin your babel version (or actually maybe we should pin the babel version?).

**Comment by raymond-h** [comment]
You were right about it being an issue in babel, it seems; as noted in https://github.com/babel/babel/issues/2098 (and other issues that it is a duplicate of), some bug crept into babel, making decorators not working properly. After preventing the issue (by not using parens in decorators), babel-eslint once again recognizes uses within decorators as uses of variables.

**Comment by RobinQu** [comment]
Still not working + 1

```
  @service({foo:'bar'}})
  async myFunc() {
    //balabala
  }
```

**Comment by hzoo** [comment]
Can you make a new issue, and post with your config, and eslint, babel-eslint, babel version? Thanks

**Comment by RobinQu** [comment]
Sorry, that's a typo. It's working perfectly.

**Comment by VanishingDante** [comment]
still not working
```
eslint -v
3.10.2
```

**Comment by uhoh-itsmaciek** [comment]
Hi,

I'm running into the exact same symptoms on a version of eslint that should have this fix (4.4.1). I'm using [mobx](https://github.com/mobxjs/mobx) with [mobx-react](https://github.com/mobxjs/mobx-react) and trying to use the `@observer` decorators. E.g., if I run the linter on this class:

```javascript
import React from 'react'

import {observer} from 'mobx-react'

export default @observer class Test extends React.Component {
  render () {
    return (
      <div>hello</div>
    )
  }
}
```

I get

```
  3:9  error  'observer' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

This is my `.eslintrc`:

```javascript
{
  "parser": "babel-eslint",
  "plugins": ["react"],
  "extends": ["standard", "standard-jsx", "plugin:react/recommended"],
  "rules": {
    "comma-dangle": ["off", "always-multiline"],
  },
  "env": {
    "browser": true,
  },
}
```

And this is my `.babelrc` in case that's relevant:

```javascript
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["transform-decorators-legacy"]
}
```

Any ideas? This actually seems to work fine, but the `@observable` stuff trips up eslint.

**Comment by uhoh-itsmaciek** [comment]
So if anyone else runs into the above: I had `babel-eslint` configured as the parser, but did not actually have the module installed. I don't know why I was getting this error instead of something more sane, but clearly that's an eslint issue an not a babel-eslint one. Sorry for the noise. Hopefully my post can help others.

**Comment by frangeris** [comment]
Hey guys, why is this still happening?

```
"babel-eslint": "^8.2.1",
"eslint": "^4.16.0",
```

Error 1: `action` is defined but never used. (no-unused-vars)
Error 2: `refreshing` is not defined. (no-undef)

![image](https://user-images.githubusercontent.com/811381/35406376-815864c6-01e7-11e8-92f9-fd4a47f59a97.png)

@uhoh-itsmaciek I've tested with `eslint` globally but still the same...

**Comment by djErock** [comment]
Ran into this issue using version 
[
"babel-eslint": "8.2.2",  

](url)

upgraded to 
[
"babel-eslint": "8.2.3", 
](url)

Ran a "scorched earth install" and it did the trick.
